services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma

  server:
    build: .
    container_name: event-scraper-server
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - chromadb
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
      CHROMADB_URL: http://chromadb:8000

volumes:
  mongo_data:
  chroma_data:
