services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: .
    container_name: event-scraper-server
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase

volumes:
  mongo_data:
